<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Depreciacion;
use Doctrine\ORM\EntityRepository;
use Exception;

/**
 * DepreciacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepreciacionRepository extends EntityRepository
{
    public function agregarDepreciacion($data)
    {
        try{
            $em = $this->getEntityManager();
            $depreciacion = new Depreciacion();
            $depreciacion->setCodigo($data['codigo']);
            $depreciacion->setNombre($data['nombre']);
            $depreciacion->setIsActive($data['activo']);

            $em->persist($depreciacion);
            $em->flush();
            $msg = $depreciacion;

        }catch (Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La Depreciación ya existe, no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la Depreciación';
            }
        }
        return $msg;
    }

    public function modificarDepreciacion($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $depreciacion = $em->getRepository('AppBundle:Depreciacion')->find($data['idDepreciacion']);

            if (!empty($depreciacion)) {
                $depreciacion->setCodigo($data['codigo']);
                $depreciacion->setNombre($data['nombre']);
                $depreciacion->setIsActive($data['activo']);

                $em->persist($depreciacion);
                $em->flush();
                $msg = $depreciacion;
            } else {
                $msg = $depreciacion;
            }

        }catch (Exception $e)
        {
            $msg = 'Se produjo un error al modificar la Depreciación';
        }

        return $msg;
    }

    public function eliminarDepreciacion($id)
    {
        try
        {
            $em = $this->getEntityManager();
            $depreciacion = $em->getRepository('AppBundle:Depreciacion')->find($id);

            if (!empty($depreciacion)) {
                $depreciacion->setIsActive(0);
                $em->persist($depreciacion);
                $em->flush();
                $msg = $depreciacion;
            } else {
                $msg = $depreciacion;
            }

        }catch (Exception $e){

            $msg = 'Se produjo un error al eliminar la Depreciación';

        }
        return $msg;
    }
}
