<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlanEstimadoDivisionOtrosGastosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanEstimadoDivisionOtrosGastosRepository extends EntityRepository
{
    public function planOtrosGastosTotalServiciosDivisiones($data)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT SUM(e.totalOtroGasto) as total 
                FROM AppBundle:PlanEstimadoDivisionOtrosGastos e
                JOIN e.otroGasto s
                JOIN e.planEstimadoIndicadores p
                WHERE e.aprobarPrespuestoCentroCostoMesOtroGasto =:p1
                AND s.id =:p2
                AND p.id =:p3';

        $query = $em->createQuery($dql);
        $query->setParameter('p1', true);
        $query->setParameter('p2', $data['otroGasto']);
        $query->setParameter('p3', $data['idPlanEstimado']);

        $total = $query->getResult();

        return $total[0]['total'];

    }

    public function verificarAprobadoEstimadoOtroGastoDivisionMes($idPlanEstimado)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT s.id as otroGasto, d.id as division, e.aprobarPrespuestoCentroCostoMesOtroGasto as aprobado
                FROM AppBundle:PlanEstimadoDivisionOtrosGastos e
                JOIN e.planEstimadoIndicadores p
                JOIN e.otroGasto s
                JOIN e.divisionCentroCosto d
                WHERE e.aprobarPrespuestoCentroCostoMesOtroGasto = :p1 
                AND p.id = :p2';

        $query = $em->createQuery($dql);
        $query->setParameter('p1', true);
        $query->setParameter('p2', $idPlanEstimado);

        return $query->getResult();

    }
}
