<?php

namespace AppBundle\Repository;

use AppBundle\Entity\PlanEstimadoCentroCostoMesOtroIngreso;
use Doctrine\ORM\EntityRepository;
use Exception;

/**
 * PlanEstimadoCentroCostoMesOtroIngresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanEstimadoCentroCostoMesOtroIngresoRepository extends EntityRepository
{
    public function graficosOtroIngresoEstimadoCentroCostoMensualTodos($idPlanEstimado)
    {

        $em = $this->getEntityManager();

        $dql = 'SELECT d.id as division, c.nombre as centro, e.mes,e.totalOtroIngreso
                FROM AppBundle:PlanEstimadoCentroCostoMesOtroIngreso e 
                JOIN e.divisionCentroCosto d
                JOIN e.centroCosto c
                JOIN e.planEstimadoIndicadores p
                WHERE p.id = :p1
                ORDER BY e.id ASC';

        $query = $em->createQuery($dql);
        $query->setParameter('p1' , $idPlanEstimado);

        return $query->getResult();

    }

    public function graficosOtroIngresoEstimadoCentroCostoMensual($idPlanEstimado,$CentroCosto)
    {

        $em = $this->getEntityManager();

        $dql = 'SELECT e.mes,e.totalOtroIngreso
                FROM AppBundle:PlanEstimadoCentroCostoMesOtroIngreso e 
                JOIN e.centroCosto c
                JOIN e.planEstimadoIndicadores p
                WHERE c.id = :p1 
                AND p.id = :p2
                ORDER BY e.id ASC';

        $query = $em->createQuery($dql);
        $query->setParameter('p1' , $CentroCosto);
        $query->setParameter('p2' , $idPlanEstimado);

        return $query->getResult();

    }

    public function masterAgregarEstimadoOtroIngresoCentroCosto($data,$user)
    {
        $em = $this->getEntityManager();
        $em->beginTransaction();
        try{

            //agregar el presupuesto mensual para los Centros de Costos
            $estimadoCentroCosto = $this->agregarTotalEstimadoOtroIngresoCentroCosto($data);

            if(is_string($estimadoCentroCosto)) {
                $em->rollback();
                $msg = $estimadoCentroCosto;
            } else{
                //se crea la traza
                $dataTraza = array(
                    'username' => $user->getUsername(),
                    'nombre' => $user->getNombre(),
                    'operacion' => 'Asignar presupuesto mensual para un centro de costo',
                    'descripcion' => 'Se asignó el presupuesto mensual de otros ingresos  a: '.$estimadoCentroCosto->getCentroCosto()->getNombre()
                );
                $em->getRepository('AppBundle:Traza')-> guardarTraza($dataTraza);
                $em->commit();
                $msg = 'ok';
            }

        }catch (Exception $e){

            $em->rollback();
            $msg = 'Se produjo un error al asignar el presupuesto mensual por Centros de Costos del Plan de Otros Ingresos';
        }
        return $msg;
    }

    public function masterModificadorEstimadoOtroIngresoCentroCosto($data,$user)
    {
        $em = $this->getEntityManager();
        $em->beginTransaction();
        try{

            //Modificar el presupuesto mensual para las divisiones
            $estimadoCentroCosto = $this->modificarTotalEstimadoOtroIngresoCentroCosto($data);

            if(is_string($estimadoCentroCosto)) {
                $em->rollback();
                $msg = $estimadoCentroCosto;
            } else{
                //se crea la traza
                $dataTraza = array(
                    'username' => $user->getUsername(),
                    'nombre' => $user->getNombre(),
                    'operacion' => 'Modificar el presupuesto mensual por centro de costo al Plan de Otros Ingresos',
                    'descripcion' => 'Se modificó el presupuesto mensual de otros ingresos  a: '.$estimadoCentroCosto->getCentroCosto()->getNombre()
                );
                $em->getRepository('AppBundle:Traza')-> guardarTraza($dataTraza);
                $em->commit();
                $msg = 'ok';
            }

        }catch (Exception $e){

            $em->rollback();
            $msg = 'Se produjo un error al modificar el presupuesto mensual por centro de costo del Plan de Otros Ingresos';
        }
        return $msg;
    }

    public function agregarTotalEstimadoOtroIngresoCentroCosto($data)
    {
        try {
            $em = $this->getEntityManager();
            $totalEstimadoCentroCostoOtroIngreso = new PlanEstimadoCentroCostoMesOtroIngreso();
            $totalEstimadoCentroCostoOtroIngreso->setMes($data['mes']);
            $totalEstimadoCentroCostoOtroIngreso->setTotalOtroIngreso($data['presupuesto']);

            $divisionCentroCosto = $em->getRepository('AppBundle:DivisionCentroCosto')->find($data['division']);
            $totalEstimadoCentroCostoOtroIngreso->setDivisionCentroCosto($divisionCentroCosto);

            $centroCosto = $em->getRepository('AppBundle:CentroCosto')->find($data['centroCosto']);
            $totalEstimadoCentroCostoOtroIngreso->setCentroCosto($centroCosto);

            $planEstimado = $em->getRepository('AppBundle:PlanEstimadoIndicadores')->find($data['idPlanEstimado']);
            $totalEstimadoCentroCostoOtroIngreso->setPlanEstimadoIndicadores($planEstimado);

            $em->persist($totalEstimadoCentroCostoOtroIngreso);
            $em->flush();
            $msg = $totalEstimadoCentroCostoOtroIngreso;

        } catch (Exception $e) {
            if (strpos($e->getMessage(), 'Duplicate entry') > 0) {
                $msg = 'El presupuesto mensual para este centro de costo ya existe, no se puede agregar';
            } else {
                $msg = 'Se produjo un error al asignar el presupuesto mensual de este centro de costo';
            }
        }
        return $msg;
    }

    public function modificarTotalEstimadoOtroIngresoCentroCosto($data)
    {
        try {
            $em = $this->getEntityManager();
            $planEstimado = $em->getRepository('AppBundle:PlanEstimadoIndicadores')->find($data['idPlanEstimado']);
            $centroCosto = $em->getRepository('AppBundle:CentroCosto')->find($data['centroCosto']);
            $mes = $data['mes'];
            $totalEstimadoCentroCostoDepreciacion = $em->getRepository('AppBundle:PlanEstimadoCentroCostoMesDepreciacion')->findOneBy(array('mes' => $mes,'planEstimadoIndicadores' => $planEstimado, 'centroCosto' => $centroCosto));

            if (!empty($totalEstimadoCentroCostoDepreciacion)) {

                $totalEstimadoCentroCostoDepreciacion->setTotalDepreciacion($data['presupuesto']);

                $em->persist($totalEstimadoCentroCostoDepreciacion);
                $em->flush();
                $msg = $totalEstimadoCentroCostoDepreciacion;
            } else {
                $msg = $totalEstimadoCentroCostoDepreciacion;
            }

        } catch (Exception $e) {
            $msg = 'Se produjo un error al modificar el total de presupuesto mensual del centro de costo';
        }

        return $msg;
    }

    public function verificarAprobadoEstimadoOtroIngresoCentroCostoMeses($data)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT e.aprobarPrespuestoCentroCostoMesOtroIngreso
                FROM AppBundle:PlanEstimadoDivisionOtroIngreso e
                JOIN e.planEstimadoIndicadores p
                WHERE e.aprobarPrespuestoCentroCostoMesOtroIngreso = :p1 
                AND p.id = :p2';

        $query = $em->createQuery($dql);
        $query->setParameter('p1', true);
        $query->setParameter('p2', $data['idPlanEstimado']);

        return count($query->getResult());

    }

    public function graficoTotalesEstimadosCentroCostosOtrosIngresos($idPlanEstimado,$idDivision)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT c.nombre, SUM(e.totalOtroIngreso) as totalOtroIngreso
                FROM AppBundle:PlanEstimadoCentroCostoMesOtroIngreso e
                JOIN e.centroCosto c
                JOIN c.divisionCentroCosto d
                JOIN e.planEstimadoIndicadores p
                WHERE d.id =:p1
                AND p.id =:p2
                GROUP BY c.nombre';

        $query = $em->createQuery($dql);
        $query->setParameter('p1', $idDivision);
        $query->setParameter('p2', $idPlanEstimado);

        return $query->getResult();

    }

    //Funciones para el export
    public function datosExportEstimadoOtroIngresoCentroCostoMeses($idPlanEstimado)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT d.nombre as division, c.nombre as centro, e.mes, e.totalOtroIngreso as presupuesto
                FROM AppBundle:PlanEstimadoCentroCostoMesOtroIngreso e
                JOIN e.planEstimadoIndicadores p
                JOIN e.centroCosto c
                JOIN c.divisionCentroCosto d
                WHERE p.id = :p1
                ORDER BY d.nombre, c.nombre';

        $query = $em->createQuery($dql);
        $query->setParameter('p1', $idPlanEstimado);

        return $query->getResult();

    }


}
