<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioLubricanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioLubricanteRepository extends EntityRepository
{
    public function precioTipoLubricante($year,$idTipoLubricante)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT p.mes, p.precio
                FROM AppBundle:PrecioLubricante p
                JOIN p.lubricante t
                WHERE p.year =:p1
                AND t.id =:p2';

        $query = $em->createQuery($dql);
        $query->setParameter('p1', $year);
        $query->setParameter('p2', $idTipoLubricante);

        return $query->getResult();

    }

    public function precioMesTipoLubricante($year,$idTipoLubricante,$mes)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT p.mes, p.precio
                FROM AppBundle:PrecioCombustible p
                JOIN p.tipoCombustible t
                WHERE p.mes =:p1
                AND p.year =:p2
                AND t.id =:p3';

        $query = $em->createQuery($dql);
        $query->setParameter('p1', $mes);
        $query->setParameter('p2', $year);
        $query->setParameter('p2', $idTipoLubricante);

        return $query->getResult();

    }

}
