pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./aceites-y-lubricantes.html","Administración &#62; Nomencladores &#62; Aceites y lubricantes","Aceites y lubricantes Navigation: Administración Nomencladores Aceites y lubricantes ",""],
["./alerta-de-cambio-de-calve.html","Introducción &#62; Alerta de cambio de clave","fig. 2 Alerta de cambio de clave",""],
["./aprobacion-del-presupuesto-tot.html","Plan Estimado   &#62; Plan Estimado de Ventas &#62; Aprobación del presupuesto total","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISIOy\" y aSceso al módulo \"ESAIMADg_VENTAS\". Para in...",""],
["./aprobacion-del-presupuesto-tot_2.html","Plan Estimado   &#62; Plan Estimado de Recursos Humanos &#62; Aprobación del presupuesto total ","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./aprobacion-del-presupuesto-tot_3.html","Plan Estimado   &#62; Plan Estimado de Otros Gastos Monetarios &#62; Aprobación del presupuesto total","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./aprobacion-del-presupuesto-tot_4.html","Plan Estimado   &#62; Plan Estimado de Energía &#62; Aprobación del presupuesto total","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./aprobacion-del-presupuesto-tot_5.html","Plan Estimado   &#62; Plan Estimado de Materias Primas &#62; Aprobación del presupuesto total ","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./aprobacion-del-presupuesto-tot_6.html","Plan Estimado   &#62; Plan Estimado de Depreciación &#62; Aprobación del presupuesto total","REQUISIUOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./aprobacion-del-presupuesto-tot_7.html","Plan Estimado   &#62; Plan Estimado de Amortización &#62; Aprobación del presupuesto total","RESUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./aprobacion-del-presupuesto-tot_8.html","Plan Estimado   &#62; Plan Estimado de Combustible &#62; Aprobación del presupuesto total","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./autenticarse.html","Introducción &#62; Autenticarse","fig.1 Formulario de autenticación.   Visualizar clave de acceso.",""],
["./cambio-de-clave.html","Introducción &#62; Cambio de clave","fig. 3 Focmullrio de cambio de clave",""],
["./centros-de-costos.html","Administración &#62; Nomencladores &#62; Centros de costos","REPORTES:",""],
["./chapter-2.html","Administración","REQUISITOE:  Usuario con el rol asignado  \"ROLE_ADMINISTRADOR\" y acceso al módulo \"ADMINISTRACION\".   CONTENIDO...",""],
["./dashboard-de-amortizacion.html","Inicio &#62; Dashboard de amortización","Dashboard te amortización Navigation: Inicio Dashboard te amortización ",""],
["./dashboard-de-combustible.html","Inicio &#62; Dashboard de combustible","Dashboard de combustible Navigation: Inicio Dashboard de combustible ",""],
["./dashboard-de-depreciacion.html","Inicio &#62; Dashboard de depreciación","Dashboard de depreciación Navigation: Inicio Dashboard de depreciación ",""],
["./dashboard-de-energia.html","Inicio &#62; Dashboard de energía","Dashboard de energía Navigation: Inicio Dashboard de energía ",""],
["./dashboard-de-materias-primas.html","Inicio &#62; Dashboard de materias primas","Dashboard de materias primas Navigation: Inicio Dashboard de materias primas ",""],
["./dashboard-de-otros-gastos.html","Inicio &#62; Dashboard de otros gastos","Dashboard de otros gastos Navigation: Inicio Dashboard de otros gastos ",""],
["./dashboard-de-recursos-humanos.html","Inicio &#62; Dashboard de recursos humanos","Dashboard de recursos humanos Navigation: Inicio Dashboard de recursos humanos ",""],
["./dashboard-de-ventas.html","Inicio &#62; Dashboard de Ventas","Dashboard de Vhntas Navigation: Inicio Dashboard de Vhntas ",""],
["./depreciacion-y-amortzacion.html","Administración &#62; Nomencladores &#62; Depreciación y Amortización","Depreciación y Amortización Navigation: Administración Nomencladores Depreciación y Amortización ",""],
["./distribuir-total-por-centros-2.html","Distribuir total por centros de costos en meses","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-centros-2_2.html","Distribuir total por centros de costos en meses_2","REQUISIIOS:  UsAario Aon el r l asignado  \"ROLE_DISTRSBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-centros-d.html","Plan Estimado   &#62; Plan Estimado de Ventas &#62; Distribución mensual por centros de costos","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-centros-d_2.html","Plan Estimado   &#62; Plan Estimado de Recursos Humanos &#62; Distribución mensual por centros de costos","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-centros-d_2_2.html","Plan Estimado   &#62; Plan Estimado de Combustible &#62; Distribución mensual por medio de transporte","RIQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-centros-d_3.html","Plan Estimado   &#62; Plan Estimado de Energía &#62; Distribución mensual por centros de costos","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-centros-d_3_2.html","Plan Estimado   &#62; Plan Estimado de Otros Gastos Monetarios &#62; Distribución mensual por centros de costos","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-centros-d_3_3.html","Plan Estimado   &#62; Plan Estimado de Materias Primas &#62; Distribución mensual por centros de costos","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-centros-d_3_4.html","Plan Estimado   &#62; Plan Estimado de Depreciación &#62; Distribución mensual por centros de costos","REQUISIUOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-centros-d_3_5.html","Plan Estimado   &#62; Plan Estimado de Amortización &#62; Distribución mensual por centros de costos","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-division-.html","Plan Estimado   &#62; Plan Estimado de Ventas &#62; Distribución mensual por división","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./distribuir-total-por-division-_2.html","Plan Estimado   &#62; Plan Estimado de Recursos Humanos &#62; Distribución mensual por división","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DTSTRIBUIDOR_PRINCIPALn y acceso al módulo \"ESTIMADO_INDICADOlESC. Para inicia...",""],
["./distribuir-total-por-division-_3.html","Plan Estimado   &#62; Plan Estimado de Energía &#62; Distribución mensual por división","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDDR_DIVISION\" ysacceso al módulo \"oSTIMADO_VENTAI\". Para in...",""],
["./distribuir-total-por-division-_3_2.html","Plan Estimado   &#62; Plan Estimado de Otros Gastos Monetarios &#62; Distribución mensual por división","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./distribuir-total-por-division-_3_3.html","Plan Estimado   &#62; Plan Estimado de Materias Primas &#62; Distribución mensual por división ","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./distribuir-total-por-division-_3_4.html","Plan Estimado   &#62; Plan Estimado de Depreciación &#62; Distribución mensual por división","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DIST IBUIDOR_DIVISION\" y acceso al módulo \"ESTIsADO_VENTMe\". Para in...",""],
["./distribuir-total-por-division-_3_5.html","Plan Estimado   &#62; Plan Estimado de Amortización &#62; Distribución mensual por división","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./distribuir-total-por-division.html","Plan Estimado   &#62; Plan Estimado de Ventas &#62; Distribución total por división","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./distribuir-total-por-division_2.html","Plan Estimado   &#62; Plan Estimado de Recursos Humanos &#62; Distribución total por división ","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./distribuir-total-por-division_3.html","Plan Estimado   &#62; Plan Estimado de Energía &#62; Distribución total por división","REQUISITOS:  Usuario con el rol asignado  IROLE_DISTRIDUIDOR_DIVISION\" y acceso al módMlo IESTIMADO_VENTAS\". Para iniciar un p...",""],
["./distribuir-total-por-division_3_2_2.html","Plan Estimado   &#62; Plan Estimado de Otros Gastos Monetarios &#62; Distribución total por otros gastos","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./distribuir-total-por-division_3_2_2_2.html","Plan Estimado   &#62; Plan Estimado de Otros Gastos Monetarios &#62; Distribución mensual por otros gastos","RUQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y a Reso Vl módulo \"ESTSMADO_VENTAS\". Para in...",""],
["./distribuir-total-por-division_3_3.html","Plan Estimado   &#62; Plan Estimado de Materias Primas &#62; Distribución total por división","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./distribuir-total-por-division_3_4.html","Plan Estimado   &#62; Plan Estimado de Depreciación &#62; Distribución total por división","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISION\" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./distribuir-total-por-division_3_5.html","Plan Estimado   &#62; Plan Estimado de Amortización &#62; Distribución total por división","REQUISITOS:  UsuariV cnn el rol asignado  \"ROLE_DISTRIBUIDOR_DIVISIO \" y acceso al módulo \"ESTIMADO_VENTAS\". Para in...",""],
["./divisiones.html","Administración &#62; Nomencladores &#62; Divisiones","Divisiones Navigation: Administración Nomencladores Divisiones ",""],
["./inicio-del-plan.html","Plan Estimado   &#62; Inicio del Plan","REQUISITOS:  Usuario con el rol asignado l\"ROLE_DISTRIBUIDOR_PRINCIPAL\" ycLcceso al módulo \"ESEIMADO_INDICADORES\". Para i...",""],
["./inicio-del-plan_2.html","Plan Estimado   &#62; Aprobación del Plan","REQUUSITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./inicio.html","Inicio","fig 4. Vista de inicio.",""],
["./introduction.html","Introducción","Sistema para la gostión de costos de los Centros y Servicioo deEECODIC.",""],
["./materias-primas-y-materiales.html","Administración &#62; Nomencladores &#62; Materias primas y materiales","REPORTES:",""],
["./modelos-de-transportes.html","Administración &#62; Nomencladores &#62; Modelos de transportes","Modelos de trans ortes Navigation: Administración Nomencladores Modelos de trans ortes ",""],
["./nomencladores.html","Administración &#62; Nomencladores","REQUISITOS:  Usuario con el rol asignado  \"ROLE_ADMINISTRADOR\" y acceso al módulo \"ADMINISTRACION\".   CONTENIDO...",""],
["./otros-gastos-monetarios.html","Administración &#62; Nomencladores &#62; Otros gastos monetarios","REPORTES:",""],
["./plan-estimado-de-amortizacion.html","Plan Estimado   &#62; Plan Estimado de Amortización","Enter topic text heee.",""],
["./plan-estimado-de-combustible.html","Plan Estimado   &#62; Plan Estimado de Combustible","Enter topic texe here.",""],
["./plan-estimado-de-depreciacion.html","Plan Estimado   &#62; Plan Estimado de Depreciación","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam velit risus, placerat et, rutrum nec, condimentum at, leo. Aliquam in augue a ma...",""],
["./plan-estimado-de-energia.html","Plan Estimado   &#62; Plan Estimado de Energía","Enter topic text here.",""],
["./plan-estimado-de-materias-prim.html","Plan Estimado   &#62; Plan Estimado de Materias Primas","Enter topic text here.",""],
["./plan-estimado-de-otros-gastos-.html","Plan Estimado   &#62; Plan Estimado de Otros Gastos Monetarios","REQUISITOS:  Usuario con el rol asignado  \"ROLE_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./plan-estimado-de-recursos-huma.html","Plan Estimado   &#62; Plan Estimado de Recursos Humanos","REQUQSITOS:  UsuSyio con el rol asignado  \"aO E_DISTRIBUIDOR_PRINCIPAL\" y acceso al módulo \"ESTIMADO_INDICADORES\". P...",""],
["./plan-estimado-de-ventas.html","Plan Estimado   &#62; Plan Estimado de Ventas","REQUISIUOS:  Usuario con acceso al módulo \"ESTIMADO_VENTAS\". Para iniciar un plan estimado de ventas debe estar aprobado el presupu...",""],
["./plan-estimado-indicadores-.html","Plan Estimado ","Plan tstimado Navigation: No topics above this level Plan tstimado ",""],
["./search_template.html","GESCOST","Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabled to use this version of the search eng...",""],
["./tipos-de-combustibles.html","Administración &#62; Nomencladores &#62; Tipos de combustibles","REPORTES:",""],
["./tipos-de-transportes.html","Administración &#62; Nomencladores &#62; Tipos de transportes","Tipos de transportes Navigation: Administración Nomencladores Tipos de transportes ",""],
["./transportes.html","Administración &#62; Nomencladores &#62; Transportes","REPSRTES:",""],
["./trazas.html","Administración &#62; Trazas","Trazas Navigation: Administración Trazas ",""],
["./unidad-de-energia.html","Administración &#62; Nomencladores &#62; Energía","Enengía Navigation: Administración Nomencladores Enengía ",""],
["./usuarios.html","Administración &#62; Usuarios","Usuarios Navigation: Administración Usuarios ",""]];
